site_name: Tikka MasalAI
site_author: Team Tikka MasalAI

nav:
  - Home: index.md
  - Contributing: contributing.md
  - Development:
      - Code Style: development/code_style.md
      - Linting: development/ruff_ci.md
      - Containers & Compose: development/containers.md
      - Deployment: development/deployment.md
      - Model Deployment API: development/model_deployment_api.md
      - Model Deployment Component Delivery: development/model_deployment_component_delivery.md
      - Testing: development/testing.md
  - API Documentation: api.html

plugins:
  - include-markdown
  - mermaid2