name: Build and Deploy

on:
  push:
    branches:
      - cicdpipeline

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/mlops-2526q1-mds-upc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and push backend image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t ${{ env.IMAGE_PREFIX }}/tikka-backend:latest \
                      -t ${{ env.IMAGE_PREFIX }}/tikka-backend:$SHORT_SHA \
                      -f src/backend/Dockerfile .
          docker push ${{ env.IMAGE_PREFIX }}/tikka-backend:latest
          docker push ${{ env.IMAGE_PREFIX }}/tikka-backend:$SHORT_SHA

      - name: Build and push frontend image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t ${{ env.IMAGE_PREFIX }}/tikka-frontend:latest \
                      -t ${{ env.IMAGE_PREFIX }}/tikka-frontend:$SHORT_SHA \
                      -f src/frontend/Dockerfile .
          docker push ${{ env.IMAGE_PREFIX }}/tikka-frontend:latest
          docker push ${{ env.IMAGE_PREFIX }}/tikka-frontend:$SHORT_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd /home/adrian_mwh100
            ./run.sh