name: Build and Deploy

on:
  push:
    branches:
      - main
      - gcs-model-storage

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/mlops-2526q1-mds-upc

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push backend image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo '${{ secrets.GCP_SA_KEY }}' | base64 -d > /tmp/gcp-key.json
          docker buildx build --platform linux/amd64,linux/arm64 \
                      --secret id=gcp_credentials,src=/tmp/gcp-key.json \
                      --build-arg GOOGLE_CLOUD_PROJECT=academic-torch-476716-h3 \
                      -t ${{ env.IMAGE_PREFIX }}/tikka-backend:latest \
                      -t ${{ env.IMAGE_PREFIX }}/tikka-backend:$SHORT_SHA \
                      -f src/backend/Dockerfile \
                      --push .
          rm /tmp/gcp-key.json

      - name: Build and push frontend image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker buildx build --platform linux/amd64,linux/arm64 \
                      -t ${{ env.IMAGE_PREFIX }}/tikka-frontend:latest \
                      -t ${{ env.IMAGE_PREFIX }}/tikka-frontend:$SHORT_SHA \
                      -f src/frontend/Dockerfile \
                      --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd /home/adrian_mwh100
            ./run.sh